config/routes.rb
PartyMaster::Application.routes.draw do

  get "home/home"

  resources :party_types
  resources :invitations
  resources :locations
  resources :sessions
  resources :users
  resources :guests
  resources :parties
  resources :hosts
  resources :rsvps

  match 'host/edit' => 'hosts#edit', :as => :edit_current_host
  match 'signup' => 'hosts#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'home' => 'home#home', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'rvsp' => 'rsvps#new', :as => :rsvp
  match 'rvsp/edit' => 'rsvps#edit', :as => :edit_rsvp

  root :to => 'home#home'
  
end

app/models/party.rb
class Party < ActiveRecord::Base
    attr_accessible :host_id, :name, :party_date, :party_type_id, :location_id, :start_time, :end_time, :description, :rsvp_date 
	
	belongs_to :host
	belongs_to :location
	has_many :guests, :dependent => :destroy
	belongs_to :party_type
	has_many :invitations, :dependent => :destroy
	
	scope :all, order('name')
	scope :for_host, lambda {|host_id| where("host_id = ?", host_id) }

	validates_presence_of :host_id, :name, :location_id
	validates_time :end_time, :after => :start_time, :message => "must be after"
	validate :rsvp
	validate :date
	
	def confirmed
		self.invitations.sum('actual_attendees')
	end
		
	def expected
		self.invitations.sum('expected_attendees')
	end

	def rsvp
		return true if self.rsvp_date.nil?
		self.errors.add :rsvp_date, "must be on or before" unless (self.rsvp_date <= self.party_date)
	end	
	
	def date
		return true if self.party_date.nil?
		self.errors.add :party_date, "must be on or after" unless (self.party_date >= Time.now.strftime("%Y-%m-%d").to_date)
	end
	
end

app/models/party_type.rb
class PartyType < ActiveRecord::Base
    attr_accessible :name, :active
	
	has_many :parties
	
	scope :active, where('active = ?', true)
	scope :all, order('name')
	
	validates_presence_of :name
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
 
  before_filter :login_required
    
  def index
    @parties = Party.all.for_host(current_host).paginate :page => params[:page]
  end

  def show
    @party = Party.find(params[:id])
	@invited = @party.invitations
  end

  def new
    @party = Party.new
  end

  def create
    @party = Party.new(params[:party])
	@party.host_id = current_host.id
    if @party.save
      flash[:notice] = "Successfully created party."
      redirect_to @party
    else
      render :action => 'new'
    end
  end

  def edit
    @party = Party.find(params[:id])
  end

  def update
    @party = Party.find(params[:id])
    if @party.update_attributes(params[:party])
      flash[:notice] = "Successfully updated party."
      redirect_to party_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @party = Party.find(params[:id])
    @party.destroy
    flash[:notice] = "Successfully destroyed party."
    redirect_to parties_url
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
  def get_host_options
    Host.all.map{|p| ["#{p.first_name} #{p.last_name}", p.id] }
  end
end

app/views/parties/_form.html.erb
<%= form_for @party do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :party_type_id %><br />
    <%= f.collection_select :party_type_id, PartyType.all.active, :id, :name, :prompt => "Select ..." %>
  </p>
  <p>
    <%= f.label :party_date %><br />
    <%= f.date_select :party_date, :order => [:month, :day, :year] %>
  </p>
  <p>
    <%= f.label :location_id %><br />
    <%= f.collection_select :location_id, Location.all.for_host(current_host), :id, :name, :prompt => "Select ..." %>
  </p>
  <p>
    <%= f.label :start_time %><br />
    <%= f.time_select :start_time %>
  </p>
  <p>
    <%= f.label :end_time %><br />
    <%= f.time_select :end_time %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :rsvp_date %><br />
    <%= f.date_select :rsvp_date, :order => [:month, :day, :year], :include_blank => true %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/parties/edit.html.erb
<% title "Edit Party" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @party %> |
  <%= link_to "View All", parties_path %>
</p>

app/views/parties/index.html.erb
<h1><% title "My Parties" %></h1>

<table class="datagrid">
  <thead class="datagrid">
    <th>Name</th>
    <th>RSVPs</th>
	<th>&nbsp;</th>
  </thead>
  <% for party in @parties %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to party.name , party_path(party) %></td>
      <td><%= party.confirmed %></td>
      <td align="center">
		<% if can? :update, party %>
			<%= link_to "Edit", edit_party_path(party) %>
		<% end %>
		<% if can? :destroy, party %>
			<%= link_to "Destroy", party, :confirm => 'Are you sure?', :method => :delete %>
		<% end %>
	  </td>
    </tr>
  <% end %>
</table>

<span class="smtext">
<%= will_paginate @parties, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

<p>
	<% if can? :create, Party %>
		<%= link_to "New Party", new_party_path(party) %>
	<% end %>
</p>
<p>
  <%= link_to "Send an Invitation", new_invitation_path %>
</p>

app/views/parties/new.html.erb
<% title "New Party" %>

<%= render 'form' %>

<p><%= link_to "Back to List", parties_path %></p>

app/views/parties/show.html.erb
<% title "Party" %>

<p>
  <strong>Name:</strong>
  <%= @party.name %>
</p>
<p>
  <strong>Host:</strong>
  <%= "#{@party.host.first_name} #{@party.host.last_name}"%>
</p>
<p>
  <strong>Party Date:</strong>
  <%= @party.party_date.strftime("%B %d, %Y") %>
</p>
<p>
  <strong>Location:</strong>
  <%= @party.location.name %>
</p>
<p>
  <strong>Time:</strong>
  <%= "#{@party.start_time.strftime("%I:%M %p")} - #{@party.end_time.strftime("%I:%M %p")}" %>
</p>
<p>
  <strong>Description:</strong>
  <%= @party.description %>
</p>
<p>
	<strong>RSVP date:</strong>
    <% if @party.rsvp_date.nil? %>
		<%= "No RSVP required" %>
	<% else %>
		<%= @party.rsvp_date.strftime("%B %d, %Y") %>		
		</p>
		<p>
		  <strong>Expected Attendance:</strong>
		  <%= @party.expected %>
		</p>
		<p>
		  <strong>Confirmed Attendance:</strong>
		   <%= @party.confirmed %>
	<% end %>
</p>	
<br>
<p>
  <strong>Invited Guests:</strong><br>
	<table class="datagrid">
	  <thead class="datagrid">
		<th>Guest</th>
		<th>Expected Attendees</th>
		<th>&nbsp;</th>
	  </thead>
	  <% for invitation in @invited %>
		<tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
		  <td><%= link_to invitation.guest.name, invitation_path(invitation) %></td>
		  <td><%= invitation.expected_attendees %></td>
		  <td align="center">
		  <% if can? :update, invitation %>
			<%= link_to "Edit", edit_invitation_path(invitation) %>
		  <% end %>
		  <% if can? :destroy, invitation %>
			<%= link_to "Destroy", invitation, :confirm => 'Are you sure?', :method => :delete %>
		  <% end %>
		  </td>
		</tr>
	  <% end %>
	</table>
</p>
<p>
  <%= link_to "Edit", edit_party_path(@party) %> |
  <%= link_to "Destroy", @party, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", parties_path %>
</p>
<p>
  <%= link_to "Send an Invitation", new_invitation_path %>
</p>