config/routes.rb
PartyMaster::Application.routes.draw do

  get "home/home"

  resources :party_types
  resources :invitations
  resources :locations
  resources :sessions
  resources :users
  resources :guests
  resources :parties
  resources :hosts
  resources :rsvps

  match 'host/edit' => 'hosts#edit', :as => :edit_current_host
  match 'signup' => 'hosts#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'home' => 'home#home', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'rvsp' => 'rsvps#new', :as => :rsvp
  match 'rvsp/edit' => 'rsvps#edit', :as => :edit_rsvp

  root :to => 'home#home'
  
end

app/models/host.rb
class Host < ActiveRecord::Base
    attr_accessible :first_name, :last_name, :email, :username, :password, :password_confirmation, :role
	
	has_many :party, :dependent => :destroy
	has_many :guest, :dependent => :destroy
	has_many :location, :dependent => :destroy
	belongs_to :user
	
	attr_accessor :password
	before_save :prepare_password
	
	scope :all, :order => "last_name, first_name"
	
	validates_presence_of :first_name, :last_name, :email, :username
	validates_uniqueness_of :username, :email, :allow_blank => true
	validates_format_of :first_name, :with => /^[A-Z][a-zA-Z ]+$/
	validates_format_of :last_name, :with => /^[A-Z][a-zA-Z .-]+$/
	validates_format_of :email, :with => /^[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))$/i, :message => "is invalid"
	validates_presence_of :password, :on => :create
	validates_confirmation_of :password
	validates_length_of :password, :minimum => 4, :allow_blank => true

	ROLES = [['Administrator', :admin],['Host', :host],['Guest', :guest]]

	def role?(authorized_role)
		return false if role.nil?
		role.to_sym == authorized_role
	end
	
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.matching_password?(pass)
  end

  def matching_password?(pass)
    self.password_hash == encrypt_password(pass)
  end
  
  def check
	errors.add(:password_confirmation, "Password doesn't match confirmation") if (:password == :password_confirmation)
  end


  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end	
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

  def index
    @hosts = Host.all.paginate :page => params[:page]
  end
  
  def show
    @host = Host.find(params[:id])
  end
  
  def new
    @host = Host.new
  end

  def create
    @host = Host.new(params[:host])
    if @host.save
      session[:host_id] = @host.id
      flash[:notice] = "Thank you for signing up! You are now logged in."
      redirect_to "/"
    else
      render :action => 'new'
    end
  end

  def edit
    @host = current_host
  end

  def update
    @host = current_host
    if @host.update_attributes(params[:host])
      flash[:notice] = "Welcome, #{current_host.first_name} #{current_host.last_name}"
      redirect_to "/"
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @host = Host.find(params[:id])
    @host.destroy
    flash[:notice] = "Successfully destroyed host."
    redirect_to hosts_url
  end
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_form.html.erb
<%= form_for @host do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label :role %><br />
    <%= f.select :role, Host::ROLES %>
  </p>
  <p><%= f.submit (@host.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/hosts/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/hosts/index.html.erb
<% title "Hosts" %>

<table class="datagrid">
  <thead class="datagrid">
	<th>Host</th>
    <th>Email</th>
	<th>&nbsp;</th>
  </tr>
  <% for host in @hosts %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
	  <td><%= link_to "#{host.last_name}, #{host.first_name}", host_path(host) %></td>
      <td><%= host.email %></td>
      <td align="center">
		<%= link_to "Edit", edit_host_path(host) %>
		<%= link_to "Destroy", host, :confirm => 'Are you sure?', :method => :delete %>
	  </td>
    </tr>
  <% end %>
</table>
<p class ="supertiny"></p>

<span class="smtext">
<%= will_paginate @hosts, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

<p><%= link_to "New Host", new_host_path(host) %></p>

app/views/hosts/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/hosts/show.html.erb
<% title "Host" %>

<p>
  <strong>First Name:</strong>
  <%= @host.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @host.last_name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @host.email %>
</p>
<p>
  <strong>Username:</strong>
  <%= @host.username %>
</p>
<!-- <p>
  <strong>Password:</strong>
  <%= @host.password %>
</p> -->
<p>
  <%= link_to "Edit", edit_host_path(@host) %>
</p>