config/routes.rb
PartyMaster::Application.routes.draw do

  get "home/home"

  resources :party_types
  resources :invitations
  resources :locations
  resources :sessions
  resources :users
  resources :guests
  resources :parties
  resources :hosts
  resources :rsvps

  match 'host/edit' => 'hosts#edit', :as => :edit_current_host
  match 'signup' => 'hosts#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'home' => 'home#home', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'rvsp' => 'rsvps#new', :as => :rsvp
  match 'rvsp/edit' => 'rsvps#edit', :as => :edit_rsvp

  root :to => 'home#home'
  
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
    attr_accessible :party_id, :guest_id, :invite_code, :expected_attendees, :actual_attendees
	
	belongs_to :guest
	belongs_to :party
	
	before_create :add_invite_code
	
	scope :all, order('party_id')
	scope :for_host, lambda {|host_id| joins(:party).where("host_id = ?", host_id) }

	validates_presence_of :party_id
	validates_presence_of :guest_id, :message => "is not a number"
	validates_numericality_of :expected_attendees, :message => "is not a number"
	validates_numericality_of :expected_attendees, :only_integer => true, :message => "must be an integer"
	validates_numericality_of :expected_attendees, :greater_than => 0, :message => "must be greater than 0"

	def self.authenticate(code)
		invitation = find_by_invite_code(code)
		return invitation unless invitation.nil?
	end	
	
	def self.duplicate?(party,guest)
		invitation = find_by_party_id(party) && find_by_guest_id(guest)
		return true unless invitation.nil?
		return false
	end
	
	
	private
		def add_invite_code
			self.invite_code  = rand(36**16).to_s(36)
		end
		
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  def index
    @invitations = Invitation.all.for_host(current_host).paginate :page => params[:page]
  end

  def show
    @invitation = Invitation.find(params[:id])
  end

  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new(params[:invitation])
	unless Invitation.duplicate?(@invitation.party_id, @invitation.guest_id)
		if @invitation.save
		  FriendMailer.invited_msg(@invitation).deliver
		  flash[:notice] = "Invitation was successfully created"
		  redirect_to @invitation
		else
		  render :action => 'new'
		end
	else
	  if @invitation.update_attributes(params[:invitation])
		FriendMailer.invited_msg(@invitation).deliver
		flash[:notice] = "The invitation for this guest has been updated."
		redirect_to @invitation
	  else
		render :action => 'new'
      end
	end
  end

  def edit
    @invitation = Invitation.find(params[:id])
  end

  def update
    @invitation = Invitation.find(params[:id])
    if @invitation.update_attributes(params[:invitation])
      flash[:notice] = "The invitation for this guest has been updated."
      redirect_to invitation_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy
	
    FriendMailer.uninvited_msg(@invitation).deliver
	flash[:notice] = "Invitation was successfully destroyed"
    redirect_to invitations_url
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for @invitation do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :party_id %><br />
    <%= f.collection_select :party_id, Party.all.for_host(current_host), :id, :name, :prompt => "Select ..." %>
  </p>
  <p>
    <%= f.label :guest_id %><br />
    <%= f.collection_select :guest_id, Guest.all.for_host(current_host), :id, :name, :prompt => "Select ..." %>
  </p>
  <p>
    <%= f.label :expected_attendees %><br />
    <%= f.text_field :expected_attendees %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/invitations/edit.html.erb
<% title "Edit Invitation" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @invitation %> |
  <%= link_to "View All", invitations_path %>
</p>

app/views/invitations/index.html.erb
<h1><% title "My Invitations" %></h1>

<table class="datagrid">
  <thead class="datagrid">
    <th>Party</th>
    <th>Guest</th>
    <th>Expected Attendees</th>
	<th>&nbsp;</th>
  </thead>
  <% for invitation in @invitations %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to invitation.party.name, invitation_path(invitation) %></td>
      <td><%= link_to invitation.guest.name, invitation_path(invitation) %></td>
      <td><%= invitation.expected_attendees %></td>
      <td align="center">
	  <% if can? :update, invitation %>
		<%= link_to "Edit", edit_invitation_path(invitation) %>
	  <% end %>
	  <% if can? :destroy, invitation %>
		<%= link_to "Destroy", invitation, :confirm => 'Are you sure?', :method => :delete %>
	  <% end %>
	  </td>
    </tr>
  <% end %>
</table>

<span class="smtext">
<%= will_paginate @invitations, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

<p>
	<%= link_to "Add A New Invitation", new_invitation_path(invitation) %>
</p>
<p>
	<%= link_to "RSVP", rsvp_path %>
</p>

app/views/invitations/new.html.erb
<% title "New Invitation" %>

<%= render 'form' %>

app/views/invitations/show.html.erb
<% title "Invitation" %>

<p>
  <strong>Party:</strong>
  <%= @invitation.party.name %>
</p>
<p>
  <strong>Guest:</strong>
  <%= @invitation.guest.name %>
</p>
<p>
  <strong>Invite code:</strong>
  <%= @invitation.invite_code %>
</p>
<p>
  <strong>Expected attendees:</strong>
  <%= @invitation.expected_attendees %>
</p>

<% unless @invitation.actual_attendees.nil? %>
  <p>
	<strong>Actual attendees:</strong>
	<%= @invitation.actual_attendees %>
  </p>
<%end%>


<p>
  <%= link_to "Edit", edit_invitation_path(@invitation) %> |
  <%= link_to "Destroy", @invitation, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", invitations_path %>
</p>