config/routes.rb
PartyMaster::Application.routes.draw do

  get "home/home"

  resources :party_types
  resources :invitations
  resources :locations
  resources :sessions
  resources :users
  resources :guests
  resources :parties
  resources :hosts
  resources :rsvps

  match 'host/edit' => 'hosts#edit', :as => :edit_current_host
  match 'signup' => 'hosts#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'home' => 'home#home', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'rvsp' => 'rsvps#new', :as => :rsvp
  match 'rvsp/edit' => 'rsvps#edit', :as => :edit_rsvp

  root :to => 'home#home'
  
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
	<div id="header">
	</div>
	<div id="links">
		<ul id = "links">
			<%= link_to 'My Parties', parties_path %>
			<%= link_to 'My Guests', guests_path %>
			<%= link_to 'My Locations', locations_path %>
			<%= link_to 'My Account', edit_current_host_path %>
			<% if logged_in? %>
				<%= link_to 'Logout', logout_path %>
			<% else %>
				<%= link_to 'Login', login_path %>
			<% end %>
		</ul>
	</div>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
	<%= render :partial => "partials/footer" %> 
  </body>
</html>